# Generated by Django 5.2.9 on 2025-12-19 02:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordoc_air', '0012_activitylog_remove_tag_unique_org_tag_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('govbr', 'Gov.br - Login Único'), ('receita_federal', 'Receita Federal'), ('serasa', 'SERASA Experian'), ('cartorio', 'Cartórios (CRI/CNJ)'), ('detran', 'DETRAN'), ('tse', 'TSE - Tribunal Superior Eleitoral'), ('inss', 'INSS - Previdência'), ('ans', 'ANS - Saúde Suplementar'), ('cvm', 'CVM - Mercado Financeiro'), ('oab', 'OAB - Ordem dos Advogados'), ('crm', 'CRM - Conselho Regional de Medicina'), ('cro', 'CRO - Conselho Regional de Odontologia'), ('crea', 'CREA - Conselho Regional de Engenharia'), ('pix', 'PIX - Banco Central'), ('nfe', 'NFe/NFSe - Notas Fiscais'), ('esocial', 'eSocial - Eventos Trabalhistas'), ('caged', 'CAGED - Declarações Trabalhistas'), ('sintegra', 'SINTEGRA - Integração Fiscal'), ('jucesp', 'JUCESP - Junta Comercial'), ('custom', 'Integração Customizada')], help_text='Identificador único do serviço de integração', max_length=50, unique=True, verbose_name='Tipo de Serviço')),
                ('name', models.CharField(help_text='Nome legível do serviço', max_length=200, verbose_name='Nome do Serviço')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do que o serviço faz', verbose_name='Descrição')),
                ('base_url', models.URLField(help_text='URL base da API do serviço', max_length=500, verbose_name='URL Base')),
                ('api_version', models.CharField(blank=True, help_text='Versão da API utilizada', max_length=50, verbose_name='Versão da API')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('maintenance', 'Em Manutenção'), ('deprecated', 'Descontinuado')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('requires_auth', models.BooleanField(default=True, help_text='Indica se o serviço requer autenticação', verbose_name='Requer Autenticação')),
                ('auth_type', models.CharField(blank=True, help_text='OAuth2, API Key, JWT, etc', max_length=50, verbose_name='Tipo de Autenticação')),
                ('rate_limit', models.IntegerField(default=100, help_text='Requisições por minuto permitidas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Limite de Taxa')),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Tempo máximo de espera por resposta', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Timeout (segundos)')),
                ('retry_attempts', models.IntegerField(default=3, help_text='Número de tentativas em caso de falha', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Tentativas de Retry')),
                ('cache_ttl_seconds', models.IntegerField(default=3600, help_text='Tempo de vida do cache em segundos (0 = sem cache)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(86400)], verbose_name='TTL do Cache (segundos)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configurações específicas do serviço (JSON)', verbose_name='Configuração')),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Credenciais de acesso (API keys, secrets, etc) - CRIPTOGRAFADO', verbose_name='Credenciais')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Serviço de Integração',
                'verbose_name_plural': 'Serviços de Integração',
                'db_table': 'ordoc_integration_services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_identifier', models.CharField(db_index=True, help_text='CPF, CNPJ, ou outro identificador único da requisição', max_length=200, verbose_name='Identificador')),
                ('request_type', models.CharField(db_index=True, help_text='validate_cpf, get_company_data, etc', max_length=100, verbose_name='Tipo de Requisição')),
                ('request_params', models.JSONField(default=dict, help_text='Parâmetros enviados na requisição', verbose_name='Parâmetros da Requisição')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('success', 'Sucesso'), ('failed', 'Falhou'), ('cached', 'Cache'), ('timeout', 'Timeout'), ('rate_limited', 'Rate Limit')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('response_data', models.JSONField(blank=True, help_text='Dados retornados pela API', null=True, verbose_name='Dados da Resposta')),
                ('response_code', models.IntegerField(blank=True, help_text='Código de status HTTP da resposta', null=True, verbose_name='Código HTTP')),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro caso a requisição falhe', verbose_name='Mensagem de Erro')),
                ('execution_time_ms', models.IntegerField(blank=True, help_text='Tempo de execução em milissegundos', null=True, verbose_name='Tempo de Execução (ms)')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Tentativas de Retry')),
                ('from_cache', models.BooleanField(default=False, help_text='Indica se a resposta veio do cache', verbose_name='Do Cache')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_requests', to='ordoc_air.organization', verbose_name='Organização')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ordoc_integrations.integrationservice', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Requisição de Integração',
                'verbose_name_plural': 'Requisições de Integração',
                'db_table': 'ordoc_integration_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Chave do Cache')),
                ('identifier', models.CharField(db_index=True, help_text='CPF, CNPJ, ou outro identificador', max_length=200, verbose_name='Identificador')),
                ('request_type', models.CharField(db_index=True, max_length=100, verbose_name='Tipo de Requisição')),
                ('cached_data', models.JSONField(help_text='Dados da resposta armazenados em cache', verbose_name='Dados em Cache')),
                ('hits', models.IntegerField(default=0, help_text='Número de vezes que este cache foi utilizado', verbose_name='Hits')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expira em')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, verbose_name='Último Acesso')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='ordoc_integrations.integrationservice', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Cache de Integração',
                'verbose_name_plural': 'Caches de Integração',
                'db_table': 'ordoc_integration_cache',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationservice',
            index=models.Index(fields=['service_type'], name='idx_service_type'),
        ),
        migrations.AddIndex(
            model_name='integrationservice',
            index=models.Index(fields=['status', 'is_enabled'], name='idx_service_status'),
        ),
        migrations.AddIndex(
            model_name='integrationservice',
            index=models.Index(fields=['created_at'], name='idx_service_created'),
        ),
        migrations.AddIndex(
            model_name='integrationrequest',
            index=models.Index(fields=['service', 'status'], name='idx_request_service_status'),
        ),
        migrations.AddIndex(
            model_name='integrationrequest',
            index=models.Index(fields=['organization', 'created_at'], name='idx_request_org_created'),
        ),
        migrations.AddIndex(
            model_name='integrationrequest',
            index=models.Index(fields=['request_identifier', 'request_type'], name='idx_request_id_type'),
        ),
        migrations.AddIndex(
            model_name='integrationrequest',
            index=models.Index(fields=['user', 'created_at'], name='idx_request_user_created'),
        ),
        migrations.AddIndex(
            model_name='integrationcache',
            index=models.Index(fields=['service', 'identifier'], name='idx_cache_service_id'),
        ),
        migrations.AddIndex(
            model_name='integrationcache',
            index=models.Index(fields=['expires_at'], name='idx_cache_expires'),
        ),
        migrations.AddIndex(
            model_name='integrationcache',
            index=models.Index(fields=['cache_key'], name='idx_cache_key'),
        ),
    ]
