# Generated by Django 5.2.4 on 2025-07-22 03:49

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordoc_air', '0002_batchoperation_batchoperationitem_ocrresult_and_more'),
        ('ordoc_flow', '0003_approvalworkflow_approvalstep_approvalinstance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('A1', 'A1 - Certificado em arquivo'), ('A3', 'A3 - Certificado em token/smartcard'), ('SELF_SIGNED', 'Auto-assinado'), ('CA_ISSUED', 'Emitido por AC')], max_length=20)),
                ('subject_name', models.CharField(help_text='Nome do titular', max_length=255)),
                ('issuer_name', models.CharField(help_text='Nome da AC emissora', max_length=255)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('certificate_data', models.TextField(help_text='Certificado em formato PEM')),
                ('public_key', models.TextField(help_text='Chave pública em formato PEM')),
                ('private_key', models.TextField(blank=True, help_text='Chave privada (apenas para A1)', null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('expired', 'Expirado'), ('revoked', 'Revogado'), ('suspended', 'Suspenso')], default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Certificado padrão do usuário')),
                ('fingerprint_sha256', models.CharField(max_length=64, unique=True)),
                ('key_usage', models.JSONField(default=list, help_text='Usos permitidos da chave')),
                ('extended_key_usage', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='ordoc_air.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordoc_sign_certificates',
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_type', models.CharField(choices=[('digital', 'Assinatura Digital'), ('electronic', 'Assinatura Eletrônica'), ('biometric', 'Assinatura Biométrica')], default='digital', max_length=20)),
                ('signature_data', models.TextField(help_text='Dados da assinatura em base64')),
                ('hash_algorithm', models.CharField(default='SHA256', max_length=10)),
                ('document_hash', models.CharField(help_text='Hash do documento assinado', max_length=128)),
                ('signing_reason', models.CharField(blank=True, max_length=200)),
                ('signing_location', models.CharField(blank=True, max_length=200)),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Válida'), ('invalid', 'Inválida'), ('expired', 'Expirada'), ('revoked', 'Revogada')], default='valid', max_length=20)),
                ('validation_info', models.JSONField(default=dict, help_text='Informações de validação')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('geolocation', models.JSONField(blank=True, default=dict)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='ordoc_sign.digitalcertificate')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='ordoc_air.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_signatures', to='ordoc_air.organization')),
            ],
            options={
                'db_table': 'ordoc_sign_document_signatures',
            },
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', django_fsm.FSMField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('expired', 'Expirada'), ('rejected', 'Rejeitada')], default='draft', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_days', models.PositiveIntegerField(default=3, help_text='Dias antes do vencimento para lembrete')),
                ('require_sequential_signing', models.BooleanField(default=False)),
                ('allow_decline', models.BooleanField(default=True)),
                ('require_all_signatures', models.BooleanField(default=True)),
                ('signing_reason', models.CharField(blank=True, max_length=200)),
                ('signing_location', models.CharField(blank=True, max_length=200)),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_signature_requests', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='ordoc_air.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='ordoc_air.organization')),
            ],
            options={
                'db_table': 'ordoc_sign_signature_requests',
            },
        ),
        migrations.CreateModel(
            name='SignatureAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('request_created', 'Solicitação Criada'), ('signer_added', 'Assinante Adicionado'), ('signer_notified', 'Assinante Notificado'), ('document_viewed', 'Documento Visualizado'), ('document_signed', 'Documento Assinado'), ('signature_verified', 'Assinatura Verificada'), ('request_completed', 'Solicitação Concluída'), ('request_cancelled', 'Solicitação Cancelada'), ('certificate_uploaded', 'Certificado Carregado'), ('certificate_revoked', 'Certificado Revogado')], max_length=30)),
                ('description', models.TextField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ordoc_sign.digitalcertificate')),
                ('document_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ordoc_sign.documentsignature')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_audit_logs', to='ordoc_air.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('signature_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ordoc_sign.signaturerequest')),
            ],
            options={
                'db_table': 'ordoc_sign_signature_audit_logs',
            },
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='signature_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='ordoc_sign.signaturerequest'),
        ),
        migrations.CreateModel(
            name='SignatureRequestSigner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_type', models.CharField(choices=[('internal', 'Usuário Interno'), ('external', 'Usuário Externo'), ('email_only', 'Apenas Email')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('signing_order', models.PositiveIntegerField(default=1)),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pendente'), ('notified', 'Notificado'), ('viewed', 'Visualizado'), ('signed', 'Assinado'), ('declined', 'Recusado'), ('expired', 'Expirado')], default='pending', max_length=50)),
                ('require_certificate', models.BooleanField(default=True)),
                ('access_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_certificates', models.ManyToManyField(blank=True, to='ordoc_sign.digitalcertificate')),
                ('external_requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_assignments', to='ordoc_flow.externalrequester')),
                ('signature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='ordoc_sign.signaturerequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordoc_sign_signature_request_signers',
            },
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='ordoc_sign.signaturerequestsigner'),
        ),
        migrations.CreateModel(
            name='SignatureTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('signature_type', models.CharField(choices=[('SIMPLE', 'Assinatura Simples'), ('ADVANCED', 'Assinatura Avançada'), ('QUALIFIED', 'Assinatura Qualificada')], default='ADVANCED', max_length=20)),
                ('hash_algorithm', models.CharField(choices=[('SHA256', 'SHA-256'), ('SHA384', 'SHA-384'), ('SHA512', 'SHA-512')], default='SHA256', max_length=10)),
                ('show_signature_image', models.BooleanField(default=True)),
                ('signature_position', models.JSONField(default=dict, help_text='Posição da assinatura no documento')),
                ('signature_size', models.JSONField(default=dict, help_text='Tamanho da assinatura')),
                ('require_reason', models.BooleanField(default=False)),
                ('require_location', models.BooleanField(default=False)),
                ('require_contact_info', models.BooleanField(default=False)),
                ('require_approval', models.BooleanField(default=False)),
                ('notify_signers', models.BooleanField(default=True)),
                ('notify_completion', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_templates', to='ordoc_flow.approvalworkflow')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_signature_templates', to=settings.AUTH_USER_MODEL)),
                ('notification_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_templates', to='ordoc_flow.notificationtemplate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_templates', to='ordoc_air.organization')),
            ],
            options={
                'db_table': 'ordoc_sign_signature_templates',
            },
        ),
        migrations.AddField(
            model_name='signaturerequest',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='ordoc_sign.signaturetemplate'),
        ),
        migrations.CreateModel(
            name='SignatureBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=50)),
                ('total_documents', models.PositiveIntegerField(default=0)),
                ('processed_documents', models.PositiveIntegerField(default=0)),
                ('successful_signatures', models.PositiveIntegerField(default=0)),
                ('failed_signatures', models.PositiveIntegerField(default=0)),
                ('auto_send_notifications', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_signature_batches', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(related_name='signature_batches', to='ordoc_air.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_batches', to='ordoc_air.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_batches', to='ordoc_sign.signaturetemplate')),
            ],
            options={
                'db_table': 'ordoc_sign_signature_batches',
            },
        ),
        migrations.AddIndex(
            model_name='digitalcertificate',
            index=models.Index(fields=['organization', 'status'], name='ordoc_sign__organiz_554d95_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalcertificate',
            index=models.Index(fields=['user', 'is_default'], name='ordoc_sign__user_id_018ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalcertificate',
            index=models.Index(fields=['valid_until'], name='ordoc_sign__valid_u_329881_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalcertificate',
            index=models.Index(fields=['serial_number'], name='ordoc_sign__serial__5d4c4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='digitalcertificate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default'), name='unique_default_certificate_per_user'),
        ),
        migrations.AddIndex(
            model_name='signatureauditlog',
            index=models.Index(fields=['organization', 'created_at'], name='ordoc_sign__organiz_c7609d_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureauditlog',
            index=models.Index(fields=['signature_request'], name='ordoc_sign__signatu_d4ae67_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureauditlog',
            index=models.Index(fields=['action'], name='ordoc_sign__action_9cae31_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureauditlog',
            index=models.Index(fields=['user_email'], name='ordoc_sign__user_em_ca4acc_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequestsigner',
            index=models.Index(fields=['signature_request', 'signing_order'], name='ordoc_sign__signatu_d69068_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequestsigner',
            index=models.Index(fields=['email'], name='ordoc_sign__email_e0c2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequestsigner',
            index=models.Index(fields=['status'], name='ordoc_sign__status_9d9585_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequestsigner',
            index=models.Index(fields=['access_token'], name='ordoc_sign__access__03a9ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='signaturerequestsigner',
            constraint=models.UniqueConstraint(fields=('signature_request', 'email'), name='unique_signer_per_request'),
        ),
        migrations.AddIndex(
            model_name='documentsignature',
            index=models.Index(fields=['organization', 'status'], name='ordoc_sign__organiz_3d969c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsignature',
            index=models.Index(fields=['document'], name='ordoc_sign__documen_b82bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsignature',
            index=models.Index(fields=['signature_request'], name='ordoc_sign__signatu_afb263_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsignature',
            index=models.Index(fields=['signer'], name='ordoc_sign__signer__e2ce3d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsignature',
            index=models.Index(fields=['certificate'], name='ordoc_sign__certifi_d50f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsignature',
            index=models.Index(fields=['signed_at'], name='ordoc_sign__signed__334030_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturetemplate',
            index=models.Index(fields=['organization', 'is_active'], name='ordoc_sign__organiz_71575c_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturetemplate',
            index=models.Index(fields=['is_default'], name='ordoc_sign__is_defa_f5b34d_idx'),
        ),
        migrations.AddConstraint(
            model_name='signaturetemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_template_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='signaturerequest',
            index=models.Index(fields=['organization', 'status'], name='ordoc_sign__organiz_c3030c_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequest',
            index=models.Index(fields=['document'], name='ordoc_sign__documen_bd0ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequest',
            index=models.Index(fields=['created_by'], name='ordoc_sign__created_d0f62b_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequest',
            index=models.Index(fields=['expires_at'], name='ordoc_sign__expires_d1653f_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequest',
            index=models.Index(fields=['priority', 'status'], name='ordoc_sign__priorit_8fe20e_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturebatch',
            index=models.Index(fields=['organization', 'status'], name='ordoc_sign__organiz_9ab2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturebatch',
            index=models.Index(fields=['created_by'], name='ordoc_sign__created_5320ac_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturebatch',
            index=models.Index(fields=['created_at'], name='ordoc_sign__created_c80c1b_idx'),
        ),
    ]
