# Generated by Django 5.2.4 on 2025-07-22 04:46

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturebatch',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='signaturerequestsigner',
            name='access_token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
