# Generated by Django 5.2.4 on 2025-12-20 15:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ordoc_air", "0012_activitylog_remove_tag_unique_org_tag_slug_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True, unique=True)),
                ("document_type", models.CharField(blank=True, max_length=100)),
                ("extraction_result", models.JSONField(default=dict)),
                ("council_deliberation", models.JSONField(default=dict)),
                ("analysis_depth", models.CharField(default="full", max_length=20)),
                ("processing_time_ms", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("completed", "Completo"),
                            ("failed", "Falhou"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_analyses",
                        to="ordoc_air.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Analysis",
                "verbose_name_plural": "Document Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("user", "Usuário"),
                            ("organization", "Organização"),
                            ("sector", "Setor"),
                            ("platform", "Plataforma"),
                        ],
                        db_index=True,
                        default="user",
                        max_length=20,
                    ),
                ),
                ("document_type", models.CharField(db_index=True, max_length=100)),
                ("sector", models.CharField(blank=True, db_index=True, max_length=100)),
                ("field_name", models.CharField(blank=True, max_length=200)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("correction", "Correção"),
                            ("approval", "Aprovação"),
                            ("rejection", "Rejeição"),
                        ],
                        default="correction",
                        max_length=20,
                    ),
                ),
                ("original_value", models.TextField(blank=True)),
                ("corrected_value", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "confidence_before",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "confidence_after",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_feedbacks",
                        to="ordoc_air.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Feedback",
                "verbose_name_plural": "Knowledge Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearnedPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("user", "Usuário"),
                            ("organization", "Organização"),
                            ("sector", "Setor"),
                            ("platform", "Plataforma"),
                        ],
                        db_index=True,
                        default="organization",
                        max_length=20,
                    ),
                ),
                ("pattern_type", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "condition",
                    models.JSONField(default=dict, help_text="JSONLogic condition"),
                ),
                (
                    "action",
                    models.JSONField(default=dict, help_text="Suggested action"),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("occurrences", models.PositiveIntegerField(default=1)),
                ("sector", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "document_type",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("last_matched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learned_patterns",
                        to="ordoc_air.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learned Pattern",
                "verbose_name_plural": "Learned Patterns",
                "ordering": ["-confidence", "-occurrences"],
            },
        ),
        migrations.CreateModel(
            name="PatternFeedbackLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contribution_weight",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_patterns",
                        to="intelligence.knowledgefeedback",
                    ),
                ),
                (
                    "pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_feedbacks",
                        to="intelligence.learnedpattern",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pattern Feedback Link",
                "verbose_name_plural": "Pattern Feedback Links",
            },
        ),
        migrations.CreateModel(
            name="ProactiveAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("compliance", "Conformidade"),
                            ("pattern", "Padrão"),
                            ("suggestion", "Sugestão"),
                            ("error", "Erro"),
                        ],
                        default="suggestion",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informação"),
                            ("warning", "Aviso"),
                            ("error", "Erro"),
                            ("critical", "Crítico"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("location", models.JSONField(blank=True, null=True)),
                ("suggested_actions", models.JSONField(default=list)),
                ("document_id", models.UUIDField(db_index=True)),
                ("document_type", models.CharField(blank=True, max_length=100)),
                (
                    "user_response",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("accepted", "Aceito"),
                            ("rejected", "Rejeitado"),
                            ("modified", "Modificado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "learning_weight",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proactive_alerts",
                        to="ordoc_air.organization",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_alerts",
                        to="intelligence.learnedpattern",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proactive Alert",
                "verbose_name_plural": "Proactive Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgefeedback",
            index=models.Index(
                fields=["layer", "document_type"], name="intelligenc_layer_7f0f60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgefeedback",
            index=models.Index(
                fields=["organization", "document_type"],
                name="intelligenc_organiz_ad0c0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgefeedback",
            index=models.Index(
                fields=["processed", "created_at"],
                name="intelligenc_process_8a116e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learnedpattern",
            index=models.Index(
                fields=["layer", "pattern_type", "is_active"],
                name="intelligenc_layer_de0bd6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learnedpattern",
            index=models.Index(
                fields=["organization", "is_active"],
                name="intelligenc_organiz_6b15f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learnedpattern",
            index=models.Index(
                fields=["sector", "document_type", "is_active"],
                name="intelligenc_sector_ba0e14_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patternfeedbacklink",
            unique_together={("pattern", "feedback")},
        ),
        migrations.AddIndex(
            model_name="proactivealert",
            index=models.Index(
                fields=["document_id", "user_response"],
                name="intelligenc_documen_d23ae2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proactivealert",
            index=models.Index(
                fields=["organization", "user_response", "created_at"],
                name="intelligenc_organiz_c6db0a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proactivealert",
            index=models.Index(
                fields=["severity", "user_response"],
                name="intelligenc_severit_55f9d1_idx",
            ),
        ),
    ]
