# Generated by Django 5.2.9 on 2025-12-27 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_add_dismissed_user_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehaviorScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('personal_score', models.FloatField(default=0.0)),
                ('department_score', models.FloatField(default=0.0)),
                ('organization_score', models.FloatField(default=0.0)),
                ('sector_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Behavior Score',
                'verbose_name_plural': 'User Behavior Scores',
                'indexes': [models.Index(fields=['user', 'entity_type', 'score'], name='intelligenc_user_id_4000ec_idx')],
                'unique_together': {('user', 'entity_type', 'entity_id')},
            },
        ),
    ]
