# Generated by Django 5.2.9 on 2025-12-28 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('intelligence', '0003_userbehaviorscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentanalysis',
            old_name='document_type',
            new_name='document_type_name',
        ),
        migrations.RenameField(
            model_name='proactivealert',
            old_name='document_type',
            new_name='document_type_name',
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='document_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='proactivealert',
            name='document_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='document_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
