/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './node_modules/printer-ui/dist/**',
    './components/**/*.{ts,tsx}',
    './hooks/**/*.{ts,tsx}',
    './PrinterAir/**/*.{ts,tsx}',
    './PrinterFlow/**/*.{ts,tsx}',
    './FlowCidadao/**/*.{ts,tsx}',
    './PrinterCloud/**/*.{ts,tsx}',
  ],
  theme: {
    colors: {
      lighterBlack: '#282828',
      lightBlack: '#1D1D1D',
      black: '#000000',
      lightBlue: '#03B0EF',
      blue: '#0070C0',
      disabled: '#C2C2C2',
      green: '#00D950',
      info: '#0075FF',
      error: '#E73737',
      lighterGray: '#FAF9F9',
      lightGray: '#E0E0E0',
      gray: '#828282',
      darkGray: '#4F4F4F',
      darkerGray: '#333333',
      orange: '#F26D00',
      primaryLight: '#8EC2FF',
      primary: '#0075FF',
      primaryDark: '#004EAA',
      purple: '#6300FF',
      red: '#FF3B3B',
      darkRed: '#C30100',
      success: '#20BD1C',
      transparent: 'transparent',
      warning: '#E7C13B',
      white: '#FFFFFF',
      yellow: '#FFC000',
      cidBlueLight: '#F8F8FF',
      cidBlue: '#1B07FB',
      cidBlueDark: '#0D009B',
      cidCyanLight: '#F0FCFF',
      cidCyan: '#008CAB',
      cidCyanDark: '#00657B',
      cidError: '#B20404',
      cidGoldLight: '#FFFAF3',
      cidGold: '#D59C4E',
      cidGoldDark: '#9C733B',
      cidGrayLight: '#F8F8F8',
      cidGray: '#7B7B7B',
      cidGrayDark: '#595959',
      cidGreenLight: '#F1FEF4',
      cidGreen: '#33B679',
      cidGreenDark: '#00AF26',
      cidLoading: '#FFD260',
      cidMagentaLight: '#FFF6FA',
      cidMagenta: '#FF0B62',
      cidMagentaDark: '#CD014A',
      cidOrangeLight: '#FFF9F3',
      cidOrange: '#FF7A00',
      cidOrangeDark: '#E25700',
      cidPurpleLight: '#FCF8FC',
      cidPurple: '#AB33B0',
      cidPurpleDark: '#740379',
    },
    extend: {
      backgroundSize: {
        '500%': '500%',
      },
      animation: {
        sidebar: 'sidebar 0.3s 2',
        'gradient-x': 'gradient-x 10s ease infinite',
        'fade-out': 'fade-out 5s ease',
      },
      keyframes: {
        sidebar: {
          '0%, 100%': {
            transform: 'translateY(-15%)',
            'animation-timing-function': 'cubic-bezier(0.3, 0, 1, 0.3)',
          },
          '50%': {
            transform: ' translateY(0)',
            'animation-timing-function': 'cubic-bezier(10, 10, 0.2, 10)',
          },
        },
        'gradient-x': {
          '0%, 100%': {
            'background-size': '500% 500%',
            'background-position': 'top left',
          },
          '50%': {
            'background-size': '500% 500%',
            'background-position': 'bottom right',
          },
        },
        'fade-out': {
          from: {
            opacity: 1,
          },
          to: {
            opacity: 0,
          },
        },
      },
      fontFamily: {
        'avenir-100': ['Avenir Thin'],
        'avenir-300': ['Avenir Light'],
        'avenir-400': ['Avenir Regular'],
        'avenir-500': ['Avenir Medium'],
        'avenir-700': ['Avenir Bold'],
        'jakarta-100': ['Jakarta Thin'],
        'jakarta-300': ['Jakarta Light'],
        'jakarta-400': ['Jakarta Regular'],
        'jakarta-500': ['Jakarta Medium'],
        'jakarta-700': ['Jakarta Bold'],
        'roboto-100': ['Roboto Thin'],
        'roboto-300': ['Roboto Light'],
        'roboto-400': ['Roboto Regular'],
        'roboto-500': ['Roboto Medium'],
        'roboto-700': ['Roboto Bold'],
      },
      boxShadow: {
        default: '0 4px 13px 0 rgba(0,0,0,0.13)',
      },
    },
  },
  plugins: [require('@tailwindcss/line-clamp')],
};
