# Generated by Django 5.2.4 on 2025-07-22 03:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordoc_air', '0001_initial'),
        ('ordoc_cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('generating', 'Gerando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('scheduled', 'Agendado')], default='generating', max_length=20, verbose_name='Status')),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='html', max_length=20, verbose_name='Formato')),
                ('filters_applied', models.JSONField(default=dict, help_text='Filtros aplicados na geração do relatório', verbose_name='Filtros Aplicados')),
                ('parameters', models.JSONField(default=dict, help_text='Parâmetros específicos do relatório', verbose_name='Parâmetros')),
                ('data', models.JSONField(default=dict, help_text='Dados do relatório (cache)', verbose_name='Dados')),
                ('metadata', models.JSONField(default=dict, help_text='Metadados do relatório (estatísticas, tempo de geração, etc.)', verbose_name='Metadados')),
                ('file_path', models.CharField(blank=True, help_text='Caminho do arquivo gerado', max_length=500, null=True, verbose_name='Caminho do Arquivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo (bytes)')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('generation_time', models.DurationField(blank=True, null=True, verbose_name='Tempo de Geração')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='ordoc_cloud.ordocuser', verbose_name='Gerado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ordoc_air.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'db_table': 'ordoc_reports_reports',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Template')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('documents', 'Documentos'), ('workflow', 'Workflow'), ('users', 'Usuários'), ('system', 'Sistema'), ('custom', 'Personalizado')], max_length=50, verbose_name='Categoria')),
                ('type', models.CharField(choices=[('table', 'Tabela'), ('chart', 'Gráfico'), ('dashboard', 'Dashboard'), ('export', 'Exportação')], max_length=50, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('draft', 'Rascunho')], default='draft', max_length=20, verbose_name='Status')),
                ('query_config', models.JSONField(default=dict, help_text='Configuração da consulta SQL/ORM', verbose_name='Configuração da Consulta')),
                ('display_config', models.JSONField(default=dict, help_text='Configuração de exibição (colunas, gráficos, etc.)', verbose_name='Configuração de Exibição')),
                ('filter_config', models.JSONField(default=dict, help_text='Configuração de filtros disponíveis', verbose_name='Configuração de Filtros')),
                ('export_config', models.JSONField(default=dict, help_text='Configuração de exportação (PDF, Excel, CSV)', verbose_name='Configuração de Exportação')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('allowed_roles', models.JSONField(default=list, help_text='Roles permitidas para acessar este template', verbose_name='Roles Permitidas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_report_templates', to='ordoc_cloud.ordocuser', verbose_name='Criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='ordoc_air.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatórios',
                'db_table': 'ordoc_reports_templates',
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Agendamento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('paused', 'Pausado')], default='active', max_length=20, verbose_name='Status')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('custom', 'Personalizado')], max_length=20, verbose_name='Frequência')),
                ('cron_expression', models.CharField(blank=True, help_text='Expressão cron para agendamentos personalizados', max_length=100, null=True, verbose_name='Expressão Cron')),
                ('next_run', models.DateTimeField(verbose_name='Próxima Execução')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('default_format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=20, verbose_name='Formato Padrão')),
                ('default_filters', models.JSONField(default=dict, help_text='Filtros padrão para aplicar nos relatórios', verbose_name='Filtros Padrão')),
                ('notify_on_completion', models.BooleanField(default=True, verbose_name='Notificar ao Completar')),
                ('notify_on_error', models.BooleanField(default=True, verbose_name='Notificar em Erro')),
                ('notification_emails', models.JSONField(default=list, help_text='Lista de emails para notificação', verbose_name='Emails de Notificação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_report_schedules', to='ordoc_cloud.ordocuser', verbose_name='Criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='ordoc_air.organization', verbose_name='Organização')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ordoc_reports.reporttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Agendamento de Relatório',
                'verbose_name_plural': 'Agendamentos de Relatórios',
                'db_table': 'ordoc_reports_schedules',
            },
        ),
        migrations.CreateModel(
            name='ReportMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('generation_time', 'Tempo de Geração'), ('access_count', 'Contagem de Acessos'), ('download_count', 'Contagem de Downloads'), ('error_rate', 'Taxa de Erro'), ('user_satisfaction', 'Satisfação do Usuário'), ('custom', 'Personalizado')], max_length=50, verbose_name='Tipo de Métrica')),
                ('metric_name', models.CharField(max_length=255, verbose_name='Nome da Métrica')),
                ('metric_value', models.FloatField(verbose_name='Valor da Métrica')),
                ('metric_unit', models.CharField(blank=True, help_text='Unidade da métrica (segundos, %, etc.)', max_length=50, null=True, verbose_name='Unidade')),
                ('metadata', models.JSONField(default=dict, help_text='Metadados adicionais da métrica', verbose_name='Metadados')),
                ('period_start', models.DateTimeField(verbose_name='Início do Período')),
                ('period_end', models.DateTimeField(verbose_name='Fim do Período')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_metrics', to='ordoc_air.organization', verbose_name='Organização')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ordoc_reports.report', verbose_name='Relatório')),
                ('report_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ordoc_reports.reporttemplate', verbose_name='Template de Relatório')),
            ],
            options={
                'verbose_name': 'Métrica de Relatório',
                'verbose_name_plural': 'Métricas de Relatórios',
                'db_table': 'ordoc_reports_metrics',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ordoc_reports.reporttemplate', verbose_name='Template'),
        ),
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(help_text='Token único para acesso ao relatório', max_length=64, unique=True, verbose_name='Token de Compartilhamento')),
                ('access_type', models.CharField(choices=[('view', 'Visualizar'), ('download', 'Baixar'), ('full', 'Acesso Completo')], default='view', max_length=20, verbose_name='Tipo de Acesso')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('expired', 'Expirado'), ('revoked', 'Revogado')], default='active', max_length=20, verbose_name='Status')),
                ('is_public', models.BooleanField(default=False, help_text='Se verdadeiro, qualquer pessoa com o link pode acessar', verbose_name='Público')),
                ('password_protected', models.BooleanField(default=False, verbose_name='Protegido por Senha')),
                ('access_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha de Acesso')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('max_access_count', models.PositiveIntegerField(blank=True, help_text='Número máximo de acessos permitidos', null=True, verbose_name='Máximo de Acessos')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='Contagem de Acessos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='ordoc_reports.report', verbose_name='Relatório')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to='ordoc_cloud.ordocuser', verbose_name='Compartilhado por')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='received_report_shares', to='ordoc_cloud.ordocuser', verbose_name='Compartilhado com')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Relatório',
                'verbose_name_plural': 'Compartilhamentos de Relatórios',
                'db_table': 'ordoc_reports_shares',
                'indexes': [models.Index(fields=['share_token'], name='ordoc_repor_share_t_f80027_idx'), models.Index(fields=['status', 'expires_at'], name='ordoc_repor_status_292bf5_idx'), models.Index(fields=['report'], name='ordoc_repor_report__ea1a8c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['organization', 'category'], name='ordoc_repor_organiz_8ddeac_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['status', 'is_public'], name='ordoc_repor_status_a4e2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['created_at'], name='ordoc_repor_created_197699_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reporttemplate',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['organization', 'status'], name='ordoc_repor_organiz_50ebd4_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['next_run', 'status'], name='ordoc_repor_next_ru_ebc272_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['template'], name='ordoc_repor_templat_d77015_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportschedule',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='reportmetric',
            index=models.Index(fields=['organization', 'metric_type'], name='ordoc_repor_organiz_fc2a46_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmetric',
            index=models.Index(fields=['report_template', 'metric_type'], name='ordoc_repor_report__7620ec_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmetric',
            index=models.Index(fields=['period_start', 'period_end'], name='ordoc_repor_period__7e96a9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmetric',
            index=models.Index(fields=['created_at'], name='ordoc_repor_created_870016_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', 'status'], name='ordoc_repor_organiz_b7414a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['template', 'status'], name='ordoc_repor_templat_4fcbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by'], name='ordoc_repor_generat_eceee7_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='ordoc_repor_created_b5984c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['scheduled_at'], name='ordoc_repor_schedul_18c908_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['expires_at'], name='ordoc_repor_expires_d831b0_idx'),
        ),
    ]
