version: 0.2

env:
  secrets-manager:
    BUNDLE_GEMS__CONTRIBSYS__COM: 'production/printer-cloud-api/build:BUNDLE_GEMS__CONTRIBSYS__COM'
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 698497033648.dkr.ecr.sa-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker build -t 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/web:$CODEBUILD_RESOLVED_SOURCE_VERSION -t 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/web:latest --build-arg BUNDLE_GEMS__CONTRIBSYS__COM .
      - echo "FROM 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/web:$CODEBUILD_RESOLVED_SOURCE_VERSION\nCMD [\".docker/exec/start-worker.sh\"]" | docker build -t 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/worker:$CODEBUILD_RESOLVED_SOURCE_VERSION -t 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/worker:latest -
      - echo "FROM 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/web:$CODEBUILD_RESOLVED_SOURCE_VERSION\nCMD [\".docker/exec/start-ocr.sh\"]" | docker build -t 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/ocr:$CODEBUILD_RESOLVED_SOURCE_VERSION -t 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/ocr:latest -
      - echo "FROM 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/web:$CODEBUILD_RESOLVED_SOURCE_VERSION\nCMD [\".docker/exec/start-solr.sh\"]" | docker build -t 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/solr:$CODEBUILD_RESOLVED_SOURCE_VERSION -t 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/solr:latest -
      - echo "FROM 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/web:$CODEBUILD_RESOLVED_SOURCE_VERSION\nCMD [\".docker/exec/start-driver.sh\"]" | docker build -t 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/driver:$CODEBUILD_RESOLVED_SOURCE_VERSION -t 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/driver:latest -
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/web:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/web:latest
      - docker push 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/worker:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/worker:latest
      - docker push 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/ocr:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/ocr:latest
      - docker push 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/solr:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/solr:latest
      - docker push 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/driver:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/driver:latest
      - printf "[{\"name\":\"web\",\"imageUri\":\"698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/web:$CODEBUILD_RESOLVED_SOURCE_VERSION\"}]" > printer-cloud-api-staging-web.json
      - printf "[{\"name\":\"worker\",\"imageUri\":\"698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/worker:$CODEBUILD_RESOLVED_SOURCE_VERSION\"}]" > printer-cloud-api-staging-worker.json
      - printf "[{\"name\":\"ocr\",\"imageUri\":\"698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/ocr:$CODEBUILD_RESOLVED_SOURCE_VERSION\"}]" > printer-cloud-api-staging-ocr.json
      - printf "[{\"name\":\"solr\",\"imageUri\":\"698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/solr:$CODEBUILD_RESOLVED_SOURCE_VERSION\"}]" > printer-cloud-api-staging-solr.json
      - printf "[{\"name\":\"driver\",\"imageUri\":\"698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/driver:$CODEBUILD_RESOLVED_SOURCE_VERSION\"}]" > printer-cloud-api-staging-driver.json
      - printf "[{\"name\":\"web\",\"imageUri\":\"698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/web:$CODEBUILD_RESOLVED_SOURCE_VERSION\"}]" > printer-cloud-api-production-web.json
      - printf "[{\"name\":\"worker\",\"imageUri\":\"698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/worker:$CODEBUILD_RESOLVED_SOURCE_VERSION\"}]" > printer-cloud-api-production-worker.json
      - printf "[{\"name\":\"ocr\",\"imageUri\":\"698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/ocr:$CODEBUILD_RESOLVED_SOURCE_VERSION\"}]" > printer-cloud-api-production-ocr.json
      - printf "[{\"name\":\"solr\",\"imageUri\":\"698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/solr:$CODEBUILD_RESOLVED_SOURCE_VERSION\"}]" > printer-cloud-api-production-solr.json
      - printf "[{\"name\":\"driver\",\"imageUri\":\"698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/driver:$CODEBUILD_RESOLVED_SOURCE_VERSION\"}]" > printer-cloud-api-production-driver.json

artifacts:
  files:
    - printer-cloud-api-staging-web.json
    - printer-cloud-api-staging-worker.json
    - printer-cloud-api-staging-ocr.json
    - printer-cloud-api-staging-solr.json
    - printer-cloud-api-staging-driver.json
    - printer-cloud-api-production-web.json
    - printer-cloud-api-production-worker.json
    - printer-cloud-api-production-ocr.json
    - printer-cloud-api-production-solr.json
    - printer-cloud-api-production-driver.json
