version: "3.9"
services:
  web:
    image: 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/web
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - worker
    networks:
      - end_to_end
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    image: 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/worker
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ocr:
    image: 698497033648.dkr.ecr.sa-east-1.amazonaws.com/printer-cloud-api/ocr
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:14
    volumes:
      - printer_cloud-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  redis:
    image: redis:latest

volumes:
  printer_cloud-postgres:
  bundle:
networks:
  end_to_end:
    external: true
