source 'https://gems.contribsys.com/' do
  # Simple, efficient background processing for Ruby
  gem 'sidekiq-pro'
end

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.2', '>= 6.1.2.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# An extension to the sidekiq message processing to track your jobs
gem 'sidekiq-status'
# Scheduler / Cron for Sidekiq jobs
gem 'sidekiq-cron'

# AASM - State machines for Ruby classes (plain Ruby, ActiveRecord, Mongoid, NoBrainer, Dynamoid)
gem 'aasm', '~> 5.2.0'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# Flexible authentication solution for Rails with Warden.
gem 'devise'

# A ruby implementation of the RFC 7519 OAuth JSON Web Token (JWT) standard.
gem 'jwt'

# The authorization Gem for Ruby on Rails.
gem 'cancancan'

# ActiveModel::Serializer implementation and Rails hooks
gem 'active_model_serializers', '~> 0.10.0'

## Gemfile for Rails 3+, Sinatra, and Merb
gem 'will_paginate', '~> 3.1.0'

## pg_search builds ActiveRecord named scopes that take advantage of PostgreSQL’s full text search
gem 'pg_search'

## 🎉 Makes http fun again!
gem 'httparty'

# Tesseract Gem
gem 'rtesseract'

## The PDF::Reader library implements a PDF parser conforming as much as possible to the PDF specification from Adobe.
gem 'pdf-reader'

# Fast, Nimble PDF Writer for Ruby
gem 'prawn'

## PDF generator (from HTML) plugin for Ruby on Rails
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'

# A Pure ruby library to merge PDF files, number pages and maybe more...
gem 'combine_pdf'

# mini replacement for RMagick
gem 'mini_magick'

# A Ruby library that encodes QR Codes
gem 'rqrcode', '~> 2.0'

## The official AWS SDK for Ruby.
gem 'aws-sdk-firehose'
gem 'aws-sdk-s3', require: false
gem 'aws-sdk-sns'
gem 'aws-sdk-sqs'

## Repository for collecting Locale data for Ruby on Rails I18n as well as other interesting, Rails related I18n stuff
gem 'rails-i18n', '~> 6.0.0'

# 🃏🗑 Soft deletes for ActiveRecord done right
gem 'discard', '~> 1.2'

## Validate, generate and format CPF/CNPJ numbers. Include command-line tools.
gem 'cpf_cnpj'

## A Ruby static code analyzer and formatter, based on the community Ruby style guide.
gem 'rubocop'

# Official Rubyzip repository
gem 'rubyzip'

# A simple gem for generating string diffs
gem 'differ'

# AWS Lambda Ruby Runtime Interface Client
gem 'aws_lambda_ric'

# A super efficient Amazon SQS thread based message processor for Ruby
gem 'shoryuken'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %I[mri mingw x64_mingw]
  # RSpec for Rails 5+
  gem 'rspec-rails', '~> 4.1.0'
  # Factory Bot ♥ Rails
  gem 'factory_bot_rails'

  # A Ruby gem to load environment variables from `.env`.
  gem 'dotenv-rails'

  ## Generates Brazilian CPF numbers for use in testing.
  gem 'cpf_faker'
  ## A library for generating fake data such as names, addresses, and phone numbers.
  gem 'faker'

  # Library for stubbing and setting expectations on HTTP requests in Ruby.
  gem 'webmock'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  # memory_profiler for ruby
  gem 'memory_profiler'
end

group :test do
  # RSpec for Sidekiq
  gem 'rspec-sidekiq'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
