update_reports:
  cron: "0 22 * * 1-5"
  description: "Update reports for each organization."
  class: "UpdateReportsWorker"
  queue: reports
  args: { organization_id: 1 }

reprocess_failed_documents:
  cron: "0 21 * * 1-5"
  description: "Reprocess documents when ocr fails."
  class: "ReprocessFailedDocumentsWorker"
  queue: default

attach_driver_corrupted_documents:
  cron: "0 21 * * 1-5"
  description: "Attach documents that failed to upload."
  class: "AttachDriverCorruptedDocuments"
  queue: default
