# Generated by Django 5.2.4 on 2025-07-22 01:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ordoc_air", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalRequester",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("active", "Ativo"),
                            ("blocked", "Bloqueado"),
                            ("inactive", "Inativo"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Empresa"
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="CPF/CNPJ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_requesters",
                        to="ordoc_air.organization",
                        verbose_name="Organização",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitante Externo",
                "verbose_name_plural": "Solicitantes Externos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("submitted", "Enviado"),
                            ("in_progress", "Em Andamento"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(default=dict, verbose_name="Dados da Solicitação"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_requests",
                        to="ordoc_air.organization",
                        verbose_name="Organização",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_requests",
                        to="ordoc_flow.externalrequester",
                        verbose_name="Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Workflow",
                "verbose_name_plural": "Solicitações de Workflow",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="externalrequester",
            index=models.Index(fields=["email"], name="ordoc_flow__email_0bab73_idx"),
        ),
        migrations.AddIndex(
            model_name="externalrequester",
            index=models.Index(
                fields=["organization", "status"], name="ordoc_flow__organiz_c21988_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalrequester",
            index=models.Index(
                fields=["created_at"], name="ordoc_flow__created_aa8940_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowrequest",
            index=models.Index(fields=["status"], name="ordoc_flow__status_0544eb_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowrequest",
            index=models.Index(
                fields=["priority"], name="ordoc_flow__priorit_94f07d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowrequest",
            index=models.Index(
                fields=["organization", "status"], name="ordoc_flow__organiz_474808_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowrequest",
            index=models.Index(
                fields=["requester", "status"], name="ordoc_flow__request_5b7332_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowrequest",
            index=models.Index(
                fields=["created_at"], name="ordoc_flow__created_fe3148_idx"
            ),
        ),
    ]
