# Generated by Django 5.2.4 on 2025-07-22 01:36

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_air', '0001_initial'),
        ('ordoc_cloud', '0001_initial'),
        ('ordoc_flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRequester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_requesters', to='ordoc_air.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Grupo de Solicitantes',
                'verbose_name_plural': 'Grupos de Solicitantes',
                'db_table': 'ordoc_flow_group_requesters',
            },
        ),
        migrations.CreateModel(
            name='GroupRequesterMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Membro'), ('coordinator', 'Coordenador'), ('manager', 'Gerente')], default='member', max_length=20, verbose_name='Função')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordoc_flow.grouprequester', verbose_name='Grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordoc_cloud.ordocuser', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Membro do Grupo',
                'verbose_name_plural': 'Membros do Grupo',
                'db_table': 'ordoc_flow_group_requester_members',
            },
        ),
        migrations.AddField(
            model_name='grouprequester',
            name='members',
            field=models.ManyToManyField(related_name='member_groups', through='ordoc_flow.GroupRequesterMember', to='ordoc_cloud.ordocuser', verbose_name='Membros'),
        ),
        migrations.CreateModel(
            name='ProcedureTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('source', models.CharField(choices=[('internal', 'Interno'), ('external', 'Externo'), ('internal_external', 'Interno e Externo')], default='internal', max_length=20, verbose_name='Origem')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status')),
                ('prn', models.CharField(max_length=500, verbose_name='PRN')),
                ('schema', models.JSONField(blank=True, default=dict, verbose_name='Schema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_templates', to='ordoc_flow.grouprequester', verbose_name='Grupo Responsável')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_templates', to='ordoc_air.organization', verbose_name='Organização')),
                ('parent_procedure_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_procedure_templates', to='ordoc_flow.proceduretemplate', verbose_name='Template Pai')),
            ],
            options={
                'verbose_name': 'Template de Procedimento',
                'verbose_name_plural': 'Templates de Procedimentos',
                'db_table': 'ordoc_flow_procedure_templates',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_number', models.CharField(max_length=50, verbose_name='Número do Processo')),
                ('procedure_template_name', models.CharField(max_length=255, verbose_name='Nome do Template')),
                ('source', models.CharField(choices=[('internal', 'Interno'), ('external', 'Externo')], default='internal', max_length=10, verbose_name='Origem')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'Alta')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('status', django_fsm.FSMField(choices=[('draft', 'Rascunho'), ('running', 'Em Execução'), ('started', 'Iniciado'), ('finished', 'Finalizado'), ('archived', 'Arquivado')], default='draft', max_length=10, verbose_name='Status')),
                ('payload', models.JSONField(blank=True, default=list, verbose_name='Dados do Procedimento')),
                ('schema', models.JSONField(blank=True, default=dict, verbose_name='Schema')),
                ('private', models.BooleanField(default=False, verbose_name='Privado')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('prn', models.CharField(max_length=500, verbose_name='PRN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_procedures', to='ordoc_cloud.ordocuser', verbose_name='Criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='ordoc_air.organization', verbose_name='Organização')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='ordoc_flow.externalrequester', verbose_name='Solicitante')),
                ('responsible_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='ordoc_flow.grouprequester', verbose_name='Grupo Responsável')),
                ('procedure_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='ordoc_flow.proceduretemplate', verbose_name='Template de Procedimento')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'db_table': 'ordoc_flow_procedures',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Rótulo')),
                ('field_type', models.CharField(choices=[('short_text', 'Texto Curto'), ('long_text', 'Texto Longo'), ('numeric', 'Numérico'), ('select_field', 'Campo de Seleção'), ('date', 'Data'), ('attachment', 'Anexo'), ('checkbox', 'Checkbox'), ('phone', 'Telefone'), ('email', 'E-mail'), ('radio', 'Radio Button'), ('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('time', 'Hora')], max_length=20, verbose_name='Tipo do Campo')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('placeholder', models.CharField(blank=True, max_length=255, verbose_name='Placeholder')),
                ('help_text', models.TextField(blank=True, verbose_name='Texto de Ajuda')),
                ('default_value', models.TextField(blank=True, verbose_name='Valor Padrão')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho Mínimo')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho Máximo')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mínimo')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Máximo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ordoc_flow.proceduretemplate', verbose_name='Template de Procedimento')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'db_table': 'ordoc_flow_fields',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status')),
                ('prn', models.CharField(max_length=500, verbose_name='PRN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='ordoc_air.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Template de Tarefa',
                'verbose_name_plural': 'Templates de Tarefas',
                'db_table': 'ordoc_flow_task_templates',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'Alta')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('status', django_fsm.FSMField(choices=[('draft', 'Rascunho'), ('running', 'Em Execução'), ('started', 'Iniciada'), ('finished', 'Finalizada'), ('refused', 'Recusada')], default='draft', max_length=10, verbose_name='Status')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('prn', models.CharField(max_length=500, verbose_name='PRN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='ordoc_flow.externalrequester', verbose_name='Responsável Individual')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='ordoc_cloud.ordocuser', verbose_name='Criado por')),
                ('group_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='ordoc_flow.grouprequester', verbose_name='Grupo Responsável')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ordoc_flow.procedure', verbose_name='Procedimento')),
                ('task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='ordoc_flow.tasktemplate', verbose_name='Template de Tarefa')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'db_table': 'ordoc_flow_tasks',
            },
        ),
        migrations.CreateModel(
            name='FieldValueOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Rótulo')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_options', to='ordoc_flow.field', verbose_name='Campo')),
            ],
            options={
                'verbose_name': 'Opção de Valor',
                'verbose_name_plural': 'Opções de Valores',
                'db_table': 'ordoc_flow_field_value_options',
                'ordering': ['order', 'label'],
                'indexes': [models.Index(fields=['field', 'is_active'], name='ordoc_flow__field_i_8e683e_idx'), models.Index(fields=['order'], name='ordoc_flow__order_1bd0d6_idx')],
                'unique_together': {('field', 'value')},
            },
        ),
        migrations.AddIndex(
            model_name='grouprequestermember',
            index=models.Index(fields=['group', 'is_active'], name='ordoc_flow__group_i_e8bb4e_idx'),
        ),
        migrations.AddIndex(
            model_name='grouprequestermember',
            index=models.Index(fields=['user', 'is_active'], name='ordoc_flow__user_id_ab9487_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grouprequestermember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='grouprequester',
            index=models.Index(fields=['organization', 'status'], name='ordoc_flow__organiz_07e7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='grouprequester',
            index=models.Index(fields=['name'], name='ordoc_flow__name_db0876_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grouprequester',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='proceduretemplate',
            index=models.Index(fields=['organization', 'status'], name='ordoc_flow__organiz_d42730_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduretemplate',
            index=models.Index(fields=['source', 'status'], name='ordoc_flow__source_d11273_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduretemplate',
            index=models.Index(fields=['parent_procedure_template'], name='ordoc_flow__parent__ab093a_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduretemplate',
            index=models.Index(fields=['prn'], name='ordoc_flow__prn_3fcdf6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proceduretemplate',
            unique_together={('prn', 'parent_procedure_template')},
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['status', 'priority'], name='ordoc_flow__status_feff63_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['organization', 'status'], name='ordoc_flow__organiz_3b1e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['procedure_template', 'status'], name='ordoc_flow__procedu_2c21fa_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['requester', 'status'], name='ordoc_flow__request_d26535_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['responsible_group', 'status'], name='ordoc_flow__respons_049808_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['created_at'], name='ordoc_flow__created_a455d4_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['deadline'], name='ordoc_flow__deadlin_0a4822_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['prn'], name='ordoc_flow__prn_a06337_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('process_number', 'procedure_template')},
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['procedure_template', 'order'], name='ordoc_flow__procedu_a218a8_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['field_type'], name='ordoc_flow__field_t_561911_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['organization', 'status'], name='ordoc_flow__organiz_f15618_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['prn'], name='ordoc_flow__prn_46fd83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktemplate',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='ordoc_flow__status_3a791d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['procedure', 'status'], name='ordoc_flow__procedu_5ec8af_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='ordoc_flow__assigne_d27ede_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['group_assignee', 'status'], name='ordoc_flow__group_a_b02868_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='ordoc_flow__created_4d62fe_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='ordoc_flow__deadlin_9a7324_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['prn'], name='ordoc_flow__prn_74aee0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'procedure')},
        ),
    ]
