# Generated by Django 5.2.4 on 2025-07-22 02:42

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ordoc_air', '0001_initial'),
        ('ordoc_cloud', '0001_initial'),
        ('ordoc_flow', '0002_grouprequester_grouprequestermember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Workflow')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('approval_type', models.CharField(choices=[('sequential', 'Sequencial'), ('parallel', 'Paralelo'), ('any_one', 'Qualquer Um'), ('majority', 'Maioria')], default='sequential', max_length=20, verbose_name='Tipo de Aprovação')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='ordoc_air.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Workflow de Aprovação',
                'verbose_name_plural': 'Workflows de Aprovação',
                'db_table': 'ordoc_flow_approval_workflows',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Etapa')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem')),
                ('step_type', models.CharField(choices=[('user', 'Usuário Específico'), ('group', 'Grupo'), ('role', 'Função/Role'), ('department', 'Departamento')], max_length=20, verbose_name='Tipo da Etapa')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('timeout_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Timeout (horas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='ordoc_flow.grouprequester', verbose_name='Grupo Aprovador')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='ordoc_cloud.ordocuser', verbose_name='Usuário Aprovador')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ordoc_flow.approvalworkflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Etapa de Aprovação',
                'verbose_name_plural': 'Etapas de Aprovação',
                'db_table': 'ordoc_flow_approval_steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('timeout', 'Timeout'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Status')),
                ('object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_approvals', to='ordoc_cloud.ordocuser', verbose_name='Solicitado por')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='ordoc_flow.approvalworkflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Instância de Aprovação',
                'verbose_name_plural': 'Instâncias de Aprovação',
                'db_table': 'ordoc_flow_approval_instances',
            },
        ),
        migrations.CreateModel(
            name='JustificationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(verbose_name='Nota')),
                ('action', models.CharField(choices=[('finish', 'Finalizar'), ('refuse', 'Recusar'), ('archive', 'Arquivar'), ('comment', 'Comentário'), ('approve', 'Aprovar'), ('reject', 'Rejeitar'), ('delegate', 'Delegar')], max_length=20, verbose_name='Ação')),
                ('object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justification_notes', to='ordoc_cloud.ordocuser', verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Nota de Justificativa',
                'verbose_name_plural': 'Notas de Justificativas',
                'db_table': 'ordoc_flow_justification_notes',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Template')),
                ('notification_type', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('push', 'Push Notification'), ('system', 'Notificação do Sistema')], max_length=10, verbose_name='Tipo de Notificação')),
                ('trigger_event', models.CharField(choices=[('task_created', 'Tarefa Criada'), ('task_assigned', 'Tarefa Atribuída'), ('task_completed', 'Tarefa Concluída'), ('task_refused', 'Tarefa Recusada'), ('procedure_started', 'Procedimento Iniciado'), ('procedure_finished', 'Procedimento Finalizado'), ('approval_requested', 'Aprovação Solicitada'), ('approval_approved', 'Aprovação Concedida'), ('approval_rejected', 'Aprovação Rejeitada'), ('deadline_approaching', 'Prazo se Aproximando'), ('deadline_exceeded', 'Prazo Excedido')], max_length=30, verbose_name='Evento Gatilho')),
                ('subject_template', models.CharField(blank=True, max_length=255, verbose_name='Template do Assunto')),
                ('body_template', models.TextField(verbose_name='Template do Corpo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('send_to_requester', models.BooleanField(default=True, verbose_name='Enviar para Solicitante')),
                ('send_to_assignee', models.BooleanField(default=True, verbose_name='Enviar para Responsável')),
                ('send_to_group', models.BooleanField(default=False, verbose_name='Enviar para Grupo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='ordoc_air.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
                'db_table': 'ordoc_flow_notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=10, verbose_name='Tipo')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Destinatário')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Destinatário')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Assunto')),
                ('body', models.TextField(verbose_name='Corpo da Mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('delivered', 'Entregue'), ('read', 'Lido')], default='pending', max_length=10, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('external_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='ordoc_flow.externalrequester', verbose_name='Destinatário Externo')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='ordoc_cloud.ordocuser', verbose_name='Destinatário')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='ordoc_flow.notificationtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'db_table': 'ordoc_flow_notification_logs',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='ordoc_cloud.ordocuser', verbose_name='Criado por')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='ordoc_flow.task', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Comentário da Tarefa',
                'verbose_name_plural': 'Comentários das Tarefas',
                'db_table': 'ordoc_flow_task_comments',
            },
        ),
        migrations.CreateModel(
            name='TaskField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255, verbose_name='Nome do Campo')),
                ('field_type', models.CharField(max_length=50, verbose_name='Tipo do Campo')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Valor')),
                ('array_values', models.JSONField(blank=True, default=list, verbose_name='Valores Array')),
                ('object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Campo da Tarefa',
                'verbose_name_plural': 'Campos das Tarefas',
                'db_table': 'ordoc_flow_task_fields',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStepInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('timeout', 'Timeout'), ('skipped', 'Pulado')], default='pending', max_length=10, verbose_name='Status')),
                ('comments', models.TextField(blank=True, verbose_name='Comentários')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Limite')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_instances', to='ordoc_flow.approvalinstance', verbose_name='Instância de Aprovação')),
                ('approval_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_instances', to='ordoc_flow.approvalstep', verbose_name='Etapa de Aprovação')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_steps', to='ordoc_cloud.ordocuser', verbose_name='Aprovado por')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_approval_steps', to='ordoc_cloud.ordocuser', verbose_name='Atribuído para')),
            ],
            options={
                'verbose_name': 'Instância de Etapa de Aprovação',
                'verbose_name_plural': 'Instâncias de Etapas de Aprovação',
                'db_table': 'ordoc_flow_approval_step_instances',
                'indexes': [models.Index(fields=['status'], name='ordoc_flow__status_4c4d25_idx'), models.Index(fields=['approval_instance'], name='ordoc_flow__approva_8b65de_idx'), models.Index(fields=['assigned_to'], name='ordoc_flow__assigne_c446bc_idx'), models.Index(fields=['approved_by'], name='ordoc_flow__approve_0d44b9_idx'), models.Index(fields=['due_date'], name='ordoc_flow__due_dat_494ca4_idx')],
                'unique_together': {('approval_instance', 'approval_step')},
            },
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['organization', 'status'], name='ordoc_flow__organiz_d3bdc7_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['approval_type'], name='ordoc_flow__approva_b2cc89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflow',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['workflow', 'order'], name='ordoc_flow__workflo_41b3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['step_type'], name='ordoc_flow__step_ty_edb903_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['approver_user'], name='ordoc_flow__approve_6454c8_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['approver_group'], name='ordoc_flow__approve_4c63a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('workflow', 'order')},
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['status'], name='ordoc_flow__status_8f9ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['workflow'], name='ordoc_flow__workflo_94462a_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='ordoc_flow__content_6ff6af_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['requested_by'], name='ordoc_flow__request_d035c5_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['created_at'], name='ordoc_flow__created_db89c6_idx'),
        ),
        migrations.AddIndex(
            model_name='justificationnote',
            index=models.Index(fields=['content_type', 'object_id'], name='ordoc_flow__content_b5b168_idx'),
        ),
        migrations.AddIndex(
            model_name='justificationnote',
            index=models.Index(fields=['created_by'], name='ordoc_flow__created_4d9450_idx'),
        ),
        migrations.AddIndex(
            model_name='justificationnote',
            index=models.Index(fields=['action'], name='ordoc_flow__action_b62732_idx'),
        ),
        migrations.AddIndex(
            model_name='justificationnote',
            index=models.Index(fields=['created_at'], name='ordoc_flow__created_bb1254_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['organization', 'is_active'], name='ordoc_flow__organiz_2910b5_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['notification_type'], name='ordoc_flow__notific_c452c7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['trigger_event'], name='ordoc_flow__trigger_39d0d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='ordoc_flow__status_a3535e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type'], name='ordoc_flow__notific_a4608e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient'], name='ordoc_flow__recipie_8594e7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['external_recipient'], name='ordoc_flow__externa_0c954a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['content_type', 'object_id'], name='ordoc_flow__content_95b21c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='ordoc_flow__created_851e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='ordoc_flow__task_id_03e156_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['created_by'], name='ordoc_flow__created_bdae52_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfield',
            index=models.Index(fields=['content_type', 'object_id'], name='ordoc_flow__content_cdc7d0_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfield',
            index=models.Index(fields=['field_name'], name='ordoc_flow__field_n_eb920c_idx'),
        ),
    ]
