# Generated by Django 5.2.9 on 2025-12-19 03:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ordoc_air', '0012_activitylog_remove_tag_unique_org_tag_slug_and_more'),
        ('ordoc_cloud', '0006_alter_policy_options_ordocuser_last_login_at_and_more'),
        ('ordoc_flow', '0003_approvalworkflow_approvalstep_approvalinstance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Documento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('document_type', models.CharField(choices=[('attachment', 'Anexo'), ('evidence', 'Evidência'), ('report', 'Relatório'), ('contract', 'Contrato'), ('invoice', 'Fatura'), ('certificate', 'Certificado'), ('other', 'Outro')], default='attachment', max_length=20, verbose_name='Tipo do Documento')),
                ('file', models.FileField(upload_to='procedure_documents/%Y/%m/%d/', verbose_name='Arquivo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamanho do Arquivo')),
                ('file_type', models.CharField(max_length=100, verbose_name='Tipo do Arquivo')),
                ('storage_key', models.CharField(blank=True, max_length=500, verbose_name='Chave de Armazenamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10, verbose_name='Status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('is_current', models.BooleanField(default=True, verbose_name='Versão Atual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documento do Procedimento',
                'verbose_name_plural': 'Documentos do Procedimento',
                'db_table': 'ordoc_flow_procedure_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Anexo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('attachment_type', models.CharField(choices=[('document', 'Documento'), ('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('spreadsheet', 'Planilha'), ('presentation', 'Apresentação'), ('other', 'Outro')], default='document', max_length=20, verbose_name='Tipo do Anexo')),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/%d/', verbose_name='Arquivo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamanho do Arquivo')),
                ('file_type', models.CharField(max_length=100, verbose_name='Tipo do Arquivo')),
                ('storage_key', models.CharField(blank=True, max_length=500, verbose_name='Chave de Armazenamento')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='task_attachments/thumbnails/%Y/%m/%d/', verbose_name='Miniatura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Anexo da Tarefa',
                'verbose_name_plural': 'Anexos da Tarefa',
                'db_table': 'ordoc_flow_task_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Criado'), ('updated', 'Atualizado'), ('status_changed', 'Status Alterado'), ('assigned', 'Atribuído'), ('commented', 'Comentado'), ('document_added', 'Documento Adicionado'), ('document_removed', 'Documento Removido'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('archived', 'Arquivado'), ('restored', 'Restaurado')], max_length=20, verbose_name='Ação')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='Valor Anterior')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='Novo Valor')),
                ('object_id', models.UUIDField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico do Workflow',
                'verbose_name_plural': 'Históricos do Workflow',
                'db_table': 'ordoc_flow_workflow_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflow_requests', to='ordoc_cloud.ordocuser', verbose_name='Atribuído para'),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadados'),
        ),
        migrations.AddIndex(
            model_name='workflowrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='ordoc_flow__assigne_a4e0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrequest',
            index=models.Index(fields=['due_date'], name='ordoc_flow__due_dat_816d43_idx'),
        ),
        migrations.AddField(
            model_name='proceduredocument',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ordoc_flow.proceduredocument', verbose_name='Documento Original'),
        ),
        migrations.AddField(
            model_name='proceduredocument',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ordoc_flow.procedure', verbose_name='Procedimento'),
        ),
        migrations.AddField(
            model_name='proceduredocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_procedure_documents', to='ordoc_cloud.ordocuser', verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ordoc_flow.task', verbose_name='Tarefa'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_task_attachments', to='ordoc_cloud.ordocuser', verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='workflowhistory',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='workflowhistory',
            name='external_performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history_actions', to='ordoc_flow.externalrequester', verbose_name='Realizado por (Externo)'),
        ),
        migrations.AddField(
            model_name='workflowhistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history_actions', to='ordoc_cloud.ordocuser', verbose_name='Realizado por'),
        ),
        migrations.AddIndex(
            model_name='proceduredocument',
            index=models.Index(fields=['procedure', 'status'], name='ordoc_flow__procedu_0de51d_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduredocument',
            index=models.Index(fields=['document_type'], name='ordoc_flow__documen_b25062_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduredocument',
            index=models.Index(fields=['uploaded_by'], name='ordoc_flow__uploade_d234b8_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduredocument',
            index=models.Index(fields=['is_current'], name='ordoc_flow__is_curr_0268a8_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduredocument',
            index=models.Index(fields=['created_at'], name='ordoc_flow__created_2d4734_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['task'], name='ordoc_flow__task_id_07cc92_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['attachment_type'], name='ordoc_flow__attachm_2ea1e2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['uploaded_by'], name='ordoc_flow__uploade_757767_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['created_at'], name='ordoc_flow__created_a298e9_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['content_type', 'object_id'], name='ordoc_flow__content_f8f252_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['action'], name='ordoc_flow__action_62ced6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['performed_by'], name='ordoc_flow__perform_b0a7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['external_performed_by'], name='ordoc_flow__externa_a71c06_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['created_at'], name='ordoc_flow__created_0eaa31_idx'),
        ),
    ]
