# Generated by Django 5.2.9 on 2025-12-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ordoc_flow', '0004_proceduredocument_taskattachment_workflowhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
