# Generated by Django 5.2.9 on 2025-12-28 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_flow', '0005_alter_notificationlog_content_type_and_more'),
        ('ordoc_sign', '0003_encrypt_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='signature_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='ordoc_sign.signaturerequest', verbose_name='Solicitação de Assinatura'),
        ),
    ]
