export const FieldTypes: Record<string, string> = {
  attachment: 'attachment',
  checkbox: 'checkbox',
  cnpj: 'cnpj',
  cpf: 'cpf',
  date: 'date',
  email: 'email',
  long_text: 'long_text',
  numeric: 'numeric',
  phone: 'phone',
  radio: 'radio',
  select_field: 'select_field',
  short_text: 'short_text',
  time: 'time',
};
