# Generated by Django 5.2.4 on 2025-07-22 00:59

import django.core.validators
import django.db.models.deletion
import django_fsm
import ordoc_air.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "prn",
                    models.CharField(max_length=500, unique=True, verbose_name="PRN"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subdepartments",
                        to="ordoc_air.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("path", models.TextField(verbose_name="Caminho")),
                (
                    "prn",
                    models.CharField(max_length=500, unique=True, verbose_name="PRN"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_directories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directories",
                        to="ordoc_air.department",
                    ),
                ),
                (
                    "parent_directory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subdirectories",
                        to="ordoc_air.directory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_directories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Diretório",
                "verbose_name_plural": "Diretórios",
                "ordering": ["path", "name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=500, verbose_name="Nome Original"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Tamanho do Arquivo"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de Conteúdo",
                    ),
                ),
                (
                    "prn",
                    models.CharField(max_length=500, unique=True, verbose_name="PRN"),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("created", "Criado"),
                            ("enqueued", "Na Fila"),
                            ("processed", "Processado"),
                            ("failed", "Falhou"),
                        ],
                        default="created",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=ordoc_air.models.document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            )
                        ],
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "processed_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ordoc_air.models.document_upload_path,
                        verbose_name="Arquivo Processado",
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto Extraído"
                    ),
                ),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Confiança OCR"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="ordoc_air.department",
                    ),
                ),
                (
                    "directory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="ordoc_air.directory",
                    ),
                ),
                (
                    "head_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="ordoc_air.document",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "corporate_name",
                    models.CharField(max_length=255, verbose_name="Razão Social"),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=14, unique=True, verbose_name="CNPJ"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "contact_name",
                    models.CharField(max_length=255, verbose_name="Nome do Contato"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Telefone do Contato"),
                ),
                ("site", models.URLField(blank=True, null=True, verbose_name="Site")),
                (
                    "subdomain",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Subdomínio"
                    ),
                ),
                (
                    "prn",
                    models.CharField(max_length=500, unique=True, verbose_name="PRN"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organização",
                "verbose_name_plural": "Organizações",
                "ordering": ["corporate_name"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="ordoc_air.organization",
            ),
        ),
        migrations.CreateModel(
            name="RecentDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_accesses",
                        to="ordoc_air.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Recente",
                "verbose_name_plural": "Documentos Recentes",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="ShareableLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=100, unique=True, verbose_name="Token"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expira em"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Contador de Acessos"
                    ),
                ),
                (
                    "max_access_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Máximo de Acessos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shareable_links",
                        to="ordoc_air.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link Compartilhável",
                "verbose_name_plural": "Links Compartilháveis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["original_filename"], name="ordoc_air_d_origina_cf4edc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="ordoc_air_d_status_067b09_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="ordoc_air_d_created_8d9185_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["directory"], name="ordoc_air_d_directo_ea34d8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="recentdocument",
            unique_together={("user", "document")},
        ),
    ]
