# Generated by Django 5.2.4 on 2025-07-22 03:30

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_air', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Operação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('operation_type', models.CharField(choices=[('move', 'Mover Documentos'), ('copy', 'Copiar Documentos'), ('delete', 'Excluir Documentos'), ('update_metadata', 'Atualizar Metadados'), ('process_ocr', 'Processar OCR'), ('change_status', 'Alterar Status'), ('export', 'Exportar Documentos'), ('index_solr', 'Indexar no Solr')], max_length=20, verbose_name='Tipo de Operação')),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=50, verbose_name='Status')),
                ('parameters', models.JSONField(default=dict, help_text='Parâmetros da operação em formato JSON', verbose_name='Parâmetros')),
                ('filters', models.JSONField(default=dict, help_text='Filtros para seleção de documentos', verbose_name='Filtros')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Total de Itens')),
                ('processed_items', models.PositiveIntegerField(default=0, verbose_name='Itens Processados')),
                ('failed_items', models.PositiveIntegerField(default=0, verbose_name='Itens com Falha')),
                ('results', models.JSONField(default=dict, help_text='Resultados da operação', verbose_name='Resultados')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='Duração Estimada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batch_operations', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_operations', to='ordoc_air.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Operação em Lote',
                'verbose_name_plural': 'Operações em Lote',
                'db_table': 'ordoc_air_batch_operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchOperationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], default='pending', max_length=20, verbose_name='Status')),
                ('result_data', models.JSONField(default=dict, help_text='Dados do resultado da operação', verbose_name='Dados do Resultado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordoc_air.batchoperation', verbose_name='Operação em Lote')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='ordoc_air.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Item de Operação em Lote',
                'verbose_name_plural': 'Itens de Operação em Lote',
                'db_table': 'ordoc_air_batch_operation_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(choices=[('tesseract', 'Tesseract'), ('google_vision', 'Google Vision API'), ('aws_textract', 'AWS Textract'), ('azure_cognitive', 'Azure Cognitive Services')], default='tesseract', max_length=20, verbose_name='Engine OCR')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Texto Extraído')),
                ('confidence_score', models.FloatField(blank=True, help_text='Pontuação de confiança (0-100)', null=True, verbose_name='Pontuação de Confiança')),
                ('metadata', models.JSONField(default=dict, help_text='Metadados do processamento OCR', verbose_name='Metadados')),
                ('language', models.CharField(default='por', help_text='Código do idioma detectado', max_length=10, verbose_name='Idioma')),
                ('processing_time', models.DurationField(blank=True, null=True, verbose_name='Tempo de Processamento')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='ordoc_air.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Resultado OCR',
                'verbose_name_plural': 'Resultados OCR',
                'db_table': 'ordoc_air_ocr_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolrIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('indexing', 'Indexando'), ('indexed', 'Indexado'), ('failed', 'Falhou'), ('outdated', 'Desatualizado')], default='pending', max_length=20, verbose_name='Status')),
                ('solr_id', models.CharField(help_text='ID do documento no Solr', max_length=255, unique=True, verbose_name='ID no Solr')),
                ('indexed_fields', models.JSONField(default=list, help_text='Lista de campos indexados', verbose_name='Campos Indexados')),
                ('boost_factor', models.FloatField(default=1.0, help_text='Fator de boost para relevância', verbose_name='Fator de Boost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='Indexado em')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solr_index', to='ordoc_air.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Índice Solr',
                'verbose_name_plural': 'Índices Solr',
                'db_table': 'ordoc_air_solr_indexes',
                'ordering': ['-indexed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='batchoperation',
            index=models.Index(fields=['organization', 'status'], name='ordoc_air_b_organiz_24086e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchoperation',
            index=models.Index(fields=['operation_type', 'status'], name='ordoc_air_b_operati_539dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='batchoperation',
            index=models.Index(fields=['created_by'], name='ordoc_air_b_created_72b986_idx'),
        ),
        migrations.AddIndex(
            model_name='batchoperation',
            index=models.Index(fields=['created_at'], name='ordoc_air_b_created_82b22f_idx'),
        ),
        migrations.AddIndex(
            model_name='batchoperationitem',
            index=models.Index(fields=['batch_operation', 'status'], name='ordoc_air_b_batch_o_988642_idx'),
        ),
        migrations.AddIndex(
            model_name='batchoperationitem',
            index=models.Index(fields=['document'], name='ordoc_air_b_documen_ce4148_idx'),
        ),
        migrations.AddIndex(
            model_name='batchoperationitem',
            index=models.Index(fields=['status'], name='ordoc_air_b_status_dcda14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batchoperationitem',
            unique_together={('batch_operation', 'document')},
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['document'], name='ordoc_air_o_documen_192afd_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['status'], name='ordoc_air_o_status_7ec106_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['engine'], name='ordoc_air_o_engine_b7899a_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['created_at'], name='ordoc_air_o_created_790e56_idx'),
        ),
        migrations.AddIndex(
            model_name='solrindex',
            index=models.Index(fields=['document'], name='ordoc_air_s_documen_6dc62d_idx'),
        ),
        migrations.AddIndex(
            model_name='solrindex',
            index=models.Index(fields=['status'], name='ordoc_air_s_status_e8cdf2_idx'),
        ),
        migrations.AddIndex(
            model_name='solrindex',
            index=models.Index(fields=['indexed_at'], name='ordoc_air_s_indexed_ff0c46_idx'),
        ),
        migrations.AddIndex(
            model_name='solrindex',
            index=models.Index(fields=['last_sync_at'], name='ordoc_air_s_last_sy_67d330_idx'),
        ),
    ]
