# Generated by Django 5.2.4 on 2025-07-23 00:00
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordoc_air", "0002_batchoperation_batchoperationitem_ocrresult_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("permission", models.CharField(max_length=100, verbose_name="Permissão")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=models.CASCADE, null=True, blank=True, related_name="air_permissions", to=settings.AUTH_USER_MODEL)),
                ("group", models.ForeignKey(on_delete=models.CASCADE, null=True, blank=True, related_name="air_permissions", to="auth.group")),
                ("directory", models.ForeignKey(on_delete=models.CASCADE, null=True, blank=True, related_name="permissions", to="ordoc_air.directory")),
                ("document", models.ForeignKey(on_delete=models.CASCADE, null=True, blank=True, related_name="permissions", to="ordoc_air.document")),
            ],
            options={
                "verbose_name": "Permissão",
                "verbose_name_plural": "Permissões",
            },
        ),
    ]
