# Generated by Django 5.2.9 on 2025-12-19 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_air', '0011_add_document_tags_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Criação'), ('read', 'Leitura'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('download', 'Download'), ('share', 'Compartilhamento'), ('archive', 'Arquivamento'), ('restore', 'Restauração'), ('move', 'Movimentação'), ('copy', 'Cópia'), ('version', 'Nova Versão'), ('permission', 'Alteração de Permissão'), ('ocr', 'Processamento OCR')], max_length=20, verbose_name='Ação')),
                ('entity_type', models.CharField(choices=[('document', 'Documento'), ('directory', 'Diretório'), ('organization', 'Organização'), ('department', 'Departamento'), ('shareable_link', 'Link Compartilhável'), ('permission', 'Permissão'), ('tag', 'Tag')], max_length=20, verbose_name='Tipo de Entidade')),
                ('entity_id', models.UUIDField(verbose_name='ID da Entidade')),
                ('entity_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nome da Entidade')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Valores Anteriores')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Novos Valores')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadados')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_org_tag_slug',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='ordoc_air_d_name_54ae73_idx',
            old_name='ordoc_air_doc_name_idx',
        ),
        migrations.AddField(
            model_name='recentdocument',
            name='access_type',
            field=models.CharField(choices=[('view', 'Visualização'), ('download', 'Download'), ('edit', 'Edição'), ('share', 'Compartilhamento')], default='view', max_length=20, verbose_name='Tipo de Acesso'),
        ),
        migrations.AddField(
            model_name='shareablelink',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Contador de Downloads'),
        ),
        migrations.AddField(
            model_name='shareablelink',
            name='max_downloads',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo de Downloads'),
        ),
        migrations.AddField(
            model_name='shareablelink',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='ordoc_air.organization'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='ordoc_air_a_entity__b39072_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='ordoc_air_a_action_556645_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='ordoc_air_a_user_id_355cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='ordoc_air_a_created_f3e8b6_idx'),
        ),
    ]
