# Generated by Django 5.2.4 on 2025-12-23 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordoc_air", "0012_activitylog_remove_tag_unique_org_tag_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorizationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome da Regra"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Correspondência Exata"),
                            ("contains", "Contém"),
                            ("regex", "Expressão Regular"),
                            ("similarity", "Similaridade (IA)"),
                        ],
                        default="contains",
                        max_length=20,
                        verbose_name="Tipo de Correspondência",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(max_length=500, verbose_name="Padrão de Busca"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization_rules",
                        to="ordoc_air.organization",
                    ),
                ),
                (
                    "target_directory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules",
                        to="ordoc_air.directory",
                        verbose_name="Mover para Diretório",
                    ),
                ),
                (
                    "target_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules",
                        to="ordoc_air.tag",
                        verbose_name="Aplicar Tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de Categorização",
                "verbose_name_plural": "Regras de Categorização",
                "ordering": ["name"],
            },
        ),
    ]
