# Generated by Django 5.2.9 on 2025-12-24 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_air', '0014_documenttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_status',
            field=models.CharField(choices=[('active', 'Ativo'), ('archived', 'Arquivado'), ('trashed', 'Lixeira'), ('draft', 'Rascunho')], db_index=True, default='active', max_length=20, verbose_name='Status do Documento'),
        ),
        migrations.AddField(
            model_name='document',
            name='hidden_for_users',
            field=models.ManyToManyField(blank=True, related_name='hidden_documents', to=settings.AUTH_USER_MODEL, verbose_name='Oculto para Usuários'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_shared',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Compartilhado'),
        ),
        migrations.AddField(
            model_name='document',
            name='needs_signature',
            field=models.BooleanField(default=False, verbose_name='Aguardando Assinatura'),
        ),
        migrations.AddField(
            model_name='document',
            name='starred',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Marcado com Estrela'),
        ),
        migrations.AddField(
            model_name='document',
            name='unread',
            field=models.BooleanField(default=True, verbose_name='Não Lido'),
        ),
    ]
