# Generated by Django 5.2.9 on 2025-12-26 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_air', '0015_document_document_status_document_hidden_for_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_documents', to=settings.AUTH_USER_MODEL, verbose_name='Favoritado por'),
        ),
    ]
