# Generated by Django 5.2.9 on 2026-01-02 15:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_air', '0017_organization_segmentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='Código de Classificação')),
                ('activity', models.CharField(max_length=255, verbose_name='Atividade/Tipo Documental')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('current_phase_years', models.PositiveIntegerField(default=2, verbose_name='Prazo Fase Corrente (anos)')),
                ('intermediate_phase_years', models.PositiveIntegerField(default=5, verbose_name='Prazo Fase Intermediária (anos)')),
                ('final_disposition', models.CharField(choices=[('eliminate', 'Eliminação'), ('permanent_custody', 'Guarda Permanente'), ('review', 'Reavaliação')], max_length=20, verbose_name='Destinação Final')),
                ('legal_basis', models.TextField(blank=True, verbose_name='Fundamento Legal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retention_schedules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_schedules', to='ordoc_air.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Tabela de Temporalidade',
                'verbose_name_plural': 'Tabelas de Temporalidade',
                'ordering': ['code', 'activity'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRetentionStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_phase_start', models.DateField(auto_now_add=True, verbose_name='Início Fase Corrente')),
                ('current_phase_end', models.DateField(blank=True, null=True, verbose_name='Fim Fase Corrente')),
                ('intermediate_phase_start', models.DateField(blank=True, null=True, verbose_name='Início Fase Intermediária')),
                ('intermediate_phase_end', models.DateField(blank=True, null=True, verbose_name='Fim Fase Intermediária')),
                ('disposition_date', models.DateField(blank=True, null=True, verbose_name='Data de Destinação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disposition_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dispositions', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_status', to='ordoc_air.document', verbose_name='Documento')),
                ('retention_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='ordoc_air.retentionschedule', verbose_name='Tabela de Temporalidade')),
            ],
            options={
                'verbose_name': 'Status de Retenção',
                'verbose_name_plural': 'Status de Retenção',
            },
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=100, verbose_name='Número do Processo/Caso')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('released', 'Liberado'), ('expired', 'Expirado')], default='active', max_length=20, verbose_name='Status')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Vigência')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de Liberação')),
                ('issuing_authority', models.CharField(max_length=255, verbose_name='Autoridade Emissora')),
                ('legal_basis', models.TextField(verbose_name='Fundamento Legal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custodians_notified', models.JSONField(blank=True, default=list, verbose_name='Custodiantes Notificados')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legal_holds', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('documents', models.ManyToManyField(related_name='legal_holds', to='ordoc_air.document', verbose_name='Documentos')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_holds', to='ordoc_air.organization', verbose_name='Organização')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_legal_holds', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
            ],
            options={
                'verbose_name': 'Legal Hold',
                'verbose_name_plural': 'Legal Holds',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='ordoc_air_l_organiz_2151d9_idx'), models.Index(fields=['case_number'], name='ordoc_air_l_case_nu_e96138_idx'), models.Index(fields=['effective_date'], name='ordoc_air_l_effecti_b83ce8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='retentionschedule',
            index=models.Index(fields=['organization', 'is_active'], name='ordoc_air_r_organiz_f1ead2_idx'),
        ),
        migrations.AddIndex(
            model_name='retentionschedule',
            index=models.Index(fields=['code'], name='ordoc_air_r_code_daa11a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentretentionstatus',
            index=models.Index(fields=['current_phase_end'], name='ordoc_air_d_current_7bd7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentretentionstatus',
            index=models.Index(fields=['intermediate_phase_end'], name='ordoc_air_d_interme_0700b5_idx'),
        ),
    ]
