# Generated by Django 5.2.9 on 2026-01-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_air', '0018_retentionschedule_documentretentionstatus_legalhold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contains_sensitive_data',
            field=models.BooleanField(default=False, help_text='CPF, RG, dados pessoais, etc', verbose_name='Contém Dados Sensíveis'),
        ),
        migrations.AddField(
            model_name='document',
            name='criticality',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='low', help_text='Nível de importância do documento', max_length=20, verbose_name='Criticidade'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, choices=[('contract', 'Contrato'), ('petition', 'Petição'), ('certificate', 'Certidão'), ('power_of_attorney', 'Procuração'), ('agreement', 'Acordo'), ('opinion', 'Parecer Jurídico'), ('ordinance', 'Portaria'), ('decree', 'Decreto'), ('law', 'Lei'), ('resolution', 'Resolução'), ('invoice', 'Nota Fiscal'), ('receipt', 'Recibo'), ('report', 'Relatório'), ('other', 'Outro')], help_text='Detectado automaticamente pela IA', max_length=50, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='document',
            name='requires_signature',
            field=models.BooleanField(default=False, help_text='Documento precisa ser assinado', verbose_name='Requer Assinatura'),
        ),
    ]
