# Generated by Django 5.2.9 on 2026-01-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_air', '0019_add_document_intelligence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deadline_date',
            field=models.DateTimeField(blank=True, help_text='Data limite para ação', null=True, verbose_name='Data do Prazo'),
        ),
        migrations.AddField(
            model_name='document',
            name='external_source_name',
            field=models.CharField(blank=True, help_text='Ex: TJSP, Portal Nacional de Licitações', max_length=200, null=True, verbose_name='Nome da Fonte Externa'),
        ),
        migrations.AddField(
            model_name='document',
            name='has_deadline',
            field=models.BooleanField(default=False, help_text='Documento tem prazo de vencimento', verbose_name='Possui Prazo'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_from_external_source',
            field=models.BooleanField(default=False, help_text='Recebido de fonte externa (Tribunal, Gov.br, etc)', verbose_name='Origem Externa'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Documento é público ou restrito', verbose_name='Público'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, choices=[('contract', 'Contrato'), ('agreement', 'Acordo'), ('addendum', 'Aditivo'), ('petition', 'Petição'), ('sentence', 'Sentença'), ('summons', 'Intimação'), ('power_of_attorney', 'Procuração'), ('opinion', 'Parecer Jurídico'), ('ordinance', 'Portaria'), ('decree', 'Decreto'), ('law', 'Lei'), ('resolution', 'Resolução'), ('edict', 'Edital'), ('invoice', 'Nota Fiscal'), ('receipt', 'Recibo'), ('tax_document', 'Documento Fiscal'), ('certificate', 'Certidão'), ('certificate_negative', 'Certidão Negativa'), ('proposal', 'Proposta'), ('report', 'Relatório'), ('minutes', 'Ata'), ('letter', 'Ofício'), ('memo', 'Memorando'), ('other', 'Outro')], help_text='Detectado automaticamente pela IA', max_length=50, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
