# Generated by Django 5.2.9 on 2026-01-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_air', '0020_add_dynamic_filter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restorable_documents', to='ordoc_air.directory', verbose_name='Pasta Original'),
        ),
    ]
