# Generated by Django 5.2.4 on 2025-07-22 01:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ordoc_air", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdocUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("active", "Ativo"),
                            ("blocked", "Bloqueado"),
                            ("inactive", "Inativo"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Número de telefone inválido",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordoc_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário Ordoc",
                "verbose_name_plural": "Usuários Ordoc",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_groups",
                        to="ordoc_air.organization",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_groups",
                        to="ordoc_cloud.ordocuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Usuários",
                "verbose_name_plural": "Grupos de Usuários",
                "ordering": ["name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "effect",
                    models.CharField(
                        choices=[("allow", "Permitir"), ("deny", "Negar")],
                        default="allow",
                        max_length=10,
                    ),
                ),
                ("service", models.CharField(max_length=100, verbose_name="Serviço")),
                ("resource", models.JSONField(default=list, verbose_name="Recursos")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("system_managed", "Gerenciado pelo Sistema"),
                            ("customer_managed", "Gerenciado pelo Cliente"),
                        ],
                        default="customer_managed",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Público"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="ordoc_air.organization",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="policies", to="ordoc_cloud.ordocuser"
                    ),
                ),
                (
                    "user_groups",
                    models.ManyToManyField(
                        blank=True, related_name="policies", to="ordoc_cloud.usergroup"
                    ),
                ),
            ],
            options={
                "verbose_name": "Política",
                "verbose_name_plural": "Políticas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserOrganizationRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("organization_manager", "Gerente da Organização"),
                            ("organization_member", "Membro da Organização"),
                            ("department_manager", "Gerente do Departamento"),
                            ("department_member", "Membro do Departamento"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="ordoc_air.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="ordoc_cloud.ordocuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role do Usuário",
                "verbose_name_plural": "Roles dos Usuários",
                "ordering": ["-created_at"],
                "unique_together": {("user", "organization", "role")},
            },
        ),
        migrations.AddField(
            model_name="ordocuser",
            name="organizations",
            field=models.ManyToManyField(
                related_name="ordoc_users",
                through="ordoc_cloud.UserOrganizationRole",
                to="ordoc_air.organization",
            ),
        ),
    ]
