# Generated by Django 5.2.4 on 2025-07-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordocuser',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Deve trocar senha'),
        ),
        migrations.AddField(
            model_name='ordocuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Senha alterada em'),
        ),
    ]
