# Generated by Django 5.2.4 on 2025-07-27 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_cloud', '0002_add_password_security_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordocuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='ordocuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='ordocuser',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de registro profissional'),
        ),
        migrations.AddField(
            model_name='ordocuser',
            name='send_welcome_email',
            field=models.BooleanField(default=True, verbose_name='Enviar email de boas-vindas'),
        ),
    ]
