# Generated by Django 5.2.4 on 2025-07-27 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_cloud', '0003_ordocuser_cpf_ordocuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordocuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato de telefone inválido. Use: (11) 99999-9999 ou 11 99999-9999', regex='^(\\(\\d{2}\\)\\s?\\d{4,5}-\\d{4}|\\d{2}\\s?\\d{4,5}-\\d{4}|\\+55\\s?\\d{2}\\s?\\d{4,5}-?\\d{4})$')]),
        ),
    ]
