# Generated by Django 5.2.9 on 2025-12-19 03:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_air', '0012_activitylog_remove_tag_unique_org_tag_slug_and_more'),
        ('ordoc_cloud', '0005_add_2fa_and_preferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Política', 'verbose_name_plural': 'Políticas'},
        ),
        migrations.AddField(
            model_name='ordocuser',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último login'),
        ),
        migrations.AddField(
            model_name='ordocuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do último login'),
        ),
        migrations.AddField(
            model_name='ordocuser',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordocuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='actions',
            field=models.JSONField(default=list, verbose_name='Ações permitidas'),
        ),
        migrations.AddField(
            model_name='policy',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Condições'),
        ),
        migrations.AddField(
            model_name='policy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to='ordoc_cloud.ordocuser'),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='policy',
            name='priority',
            field=models.PositiveIntegerField(default=100, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='policy',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_groups', to='ordoc_cloud.usergroup', verbose_name='Grupo pai'),
        ),
        migrations.AddField(
            model_name='userorganizationrole',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim da função'),
        ),
        migrations.AddField(
            model_name='userorganizationrole',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Início da função'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordocuser',
            name='organizations',
            field=models.ManyToManyField(related_name='ordoc_users', through='ordoc_cloud.UserOrganizationRole', through_fields=('user', 'organization'), to='ordoc_air.organization'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='service',
            field=models.CharField(choices=[('ordoc_air', 'OrdocAir - Documentos'), ('ordoc_flow', 'OrdocFlow - Workflows'), ('ordoc_sign', 'OrdocSign - Assinaturas'), ('ordoc_reports', 'OrdocReports - Relatórios'), ('ordoc_cloud', 'OrdocCloud - Usuários'), ('*', 'Todos os Serviços')], max_length=100, verbose_name='Serviço'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Falhou'), ('password_change', 'Alteração de Senha'), ('password_reset', 'Reset de Senha'), ('user_create', 'Criação de Usuário'), ('user_update', 'Atualização de Usuário'), ('user_delete', 'Exclusão de Usuário'), ('user_block', 'Bloqueio de Usuário'), ('user_unlock', 'Desbloqueio de Usuário'), ('role_assign', 'Atribuição de Função'), ('role_remove', 'Remoção de Função'), ('policy_create', 'Criação de Política'), ('policy_update', 'Atualização de Política'), ('policy_delete', 'Exclusão de Política'), ('2fa_enable', 'Habilitação de 2FA'), ('2fa_disable', 'Desabilitação de 2FA')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ordoc_air.organization')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to='ordoc_cloud.ordocuser')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ordoc_cloud.ordocuser')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='ordoc_cloud_action_98b0c5_idx'), models.Index(fields=['user', 'created_at'], name='ordoc_cloud_user_id_115d00_idx'), models.Index(fields=['organization', 'created_at'], name='ordoc_cloud_organiz_84323e_idx')],
            },
        ),
    ]
