# Generated by Django 5.2.9 on 2025-12-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordoc_cloud', '0007_add_refresh_token_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordocuser',
            name='view_mode',
            field=models.CharField(choices=[('personal', 'Minha Visão'), ('team', 'Visão da Equipe')], default='personal', max_length=20, verbose_name='Modo de Visualização'),
        ),
    ]
