# Generated by Django 5.2.9 on 2025-12-28 02:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ordoc_cloud', '0008_add_view_mode_to_ordoc_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('object_id', models.UUIDField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='comments/%Y/%m/%d/', verbose_name='Anexo')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Comentário Interno')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Editado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ordoc_cloud.comment', verbose_name='Resposta para')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ordoc_cloud.ordocuser', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='ordoc_cloud_content_bfcaf0_idx'), models.Index(fields=['user'], name='ordoc_cloud_user_id_1028db_idx'), models.Index(fields=['created_at'], name='ordoc_cloud_created_abf783_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link de Ação')),
                ('notification_type', models.CharField(choices=[('info', 'Informação'), ('success', 'Sucesso'), ('warning', 'Aviso'), ('error', 'Erro'), ('task_assigned', 'Tarefa Atribuída'), ('document_shared', 'Documento Compartilhado'), ('signature_requested', 'Assinatura Solicitada'), ('workflow_update', 'Atualização de Workflow')], default='info', max_length=50, verbose_name='Tipo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ordoc_cloud.ordocuser', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='ordoc_cloud_user_id_14f0ce_idx'), models.Index(fields=['created_at'], name='ordoc_cloud_created_6159d1_idx')],
            },
        ),
    ]
